"use client"

import Link from "next/link"
import { useTranslations } from "next-intl"
import { Leaf, FileText, AlertTriangle, Scale, Mail } from "lucide-react"

export default function TermsPage() {
  const t = useTranslations("footer")

  return (
    <div className="min-h-screen bg-[#FDFDFB] text-[#1A2E1A]">
      <main>
        <section className="relative py-20 bg-[#E8F5E9] overflow-hidden">
          <div className="absolute top-0 right-0 w-1/3 h-full opacity-10 pointer-events-none">
            <Leaf className="w-[400px] h-[400px] text-[#2E7D32] select-none" />
          </div>
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
            <div className="flex items-center gap-3 mb-4">
              <FileText className="w-10 h-10 text-[#2E7D32]" />
              <h1 className="font-[family-name:var(--font-merriweather)] text-4xl md:text-5xl font-bold text-[#1A2E1A]">
                {t("terms")}
              </h1>
            </div>
            <p className="text-lg text-[#4B634B]">
              Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
            </p>
          </div>
        </section>

        <section className="py-16 bg-white">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
            <div>
              <h2 className="font-[family-name:var(--font-merriweather)] text-2xl font-bold text-[#1A2E1A] mb-4">
                Acceptance of Terms
              </h2>
              <p className="text-[#4B634B] leading-relaxed">
                By accessing or using AgroAI’s website and services (including the AI diagnosis feature), you agree to
                be bound by these Terms of Service. If you do not agree, please do not use our services.
              </p>
            </div>

            <div>
              <h2 className="font-[family-name:var(--font-merriweather)] text-2xl font-bold text-[#1A2E1A] mb-4 flex items-center gap-2">
                <Scale className="w-6 h-6 text-[#2E7D32]" />
                Use of Service
              </h2>
              <p className="text-[#4B634B] leading-relaxed mb-4">
                AgroAI provides AI-powered agricultural diagnosis and related information for general guidance. You may
                use the service only for lawful purposes and in accordance with these terms. You agree not to:
              </p>
              <ul className="list-disc list-inside text-[#4B634B] space-y-2 leading-relaxed">
                <li>Misuse or attempt to gain unauthorized access to our systems or other users’ data</li>
                <li>Upload content that is illegal, harmful, or infringes others’ rights</li>
                <li>Use the service in a way that could damage, disable, or overburden our infrastructure</li>
                <li>Resell or commercially exploit the service without our written permission</li>
              </ul>
            </div>

            <div>
              <h2 className="font-[family-name:var(--font-merriweather)] text-2xl font-bold text-[#1A2E1A] mb-4">
                User Content and Data
              </h2>
              <p className="text-[#4B634B] leading-relaxed">
                You retain ownership of the content you submit (e.g., images, location, descriptions). By submitting
                content, you grant AgroAI a limited license to use, process, and store it as necessary to provide and
                improve our services, in line with our Privacy Policy.
              </p>
            </div>

            <div>
              <h2 className="font-[family-name:var(--font-merriweather)] text-2xl font-bold text-[#1A2E1A] mb-4 flex items-center gap-2">
                <AlertTriangle className="w-6 h-6 text-[#2E7D32]" />
                Disclaimer
              </h2>
              <p className="text-[#4B634B] leading-relaxed mb-4">
                AgroAI’s diagnosis and recommendations are generated by AI and are for informational and educational
                purposes only. They do not replace professional agronomic, medical, or legal advice. Crop and
                environmental outcomes depend on many factors; we do not guarantee specific results. Always consider
                consulting qualified experts for critical farming or business decisions.
              </p>
            </div>

            <div>
              <h2 className="font-[family-name:var(--font-merriweather)] text-2xl font-bold text-[#1A2E1A] mb-4">
                Limitation of Liability
              </h2>
              <p className="text-[#4B634B] leading-relaxed">
                To the fullest extent permitted by law, AgroAI and its affiliates shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages, or any loss of profits, data, or use, arising
                from your use of the service. Our total liability shall not exceed the amount you paid to us (if any) in
                the twelve months preceding the claim, or one hundred dollars, whichever is greater.
              </p>
            </div>

            <div>
              <h2 className="font-[family-name:var(--font-merriweather)] text-2xl font-bold text-[#1A2E1A] mb-4">
                Changes to Terms
              </h2>
              <p className="text-[#4B634B] leading-relaxed">
                We may update these terms from time to time. We will post the revised terms on this page and update the
                “Last updated” date. Continued use of the service after changes constitutes acceptance of the updated
                terms.
              </p>
            </div>

            <div className="pt-6 border-t border-gray-200">
              <h2 className="font-[family-name:var(--font-merriweather)] text-2xl font-bold text-[#1A2E1A] mb-4 flex items-center gap-2">
                <Mail className="w-6 h-6 text-[#2E7D32]" />
                Contact Us
              </h2>
              <p className="text-[#4B634B] leading-relaxed">
                For questions about these Terms of Service, contact us at{" "}
                <a href="mailto:legal@agroai.example.com" className="text-[#2E7D32] hover:underline font-medium">
                  legal@agroai.example.com
                </a>
                .
              </p>
            </div>

            <div className="flex justify-start">
              <Link
                href="/"
                className="inline-flex items-center gap-2 text-[#2E7D32] hover:text-[#1B5E20] font-semibold transition-colors"
              >
                ← Back to Home
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
